<option value="none" selected>Select relation</option>
<option value="Brother">Brother</option>
<option value="Daughter">Daughter</option>
<option value="Father">Father</option>
<option value="Mother">Mother</option>
<option value="Sister">Sister</option>
<option value="Son">Son</option>
<option value="Accountant">Accountant</option>
<option value="Adviser">Adviser</option>
<option value="Aunt">Aunt</option>
<option value="Brother in Law">Brother in Law</option>
<option value="Brothers partner">Brothers partner</option>
<option value="Business partner">Business partner</option>
<option value="Civil partner">Civil partner</option>
<option value="Cousin">Cousin</option>
<option value="Daughter">Daughter</option>
<option value="Daughter in Law">Daughter in Law</option>
<option value="Daughters partner">Daughters partner</option>
<option value="Estranged husband">Estranged husband</option>
<option value="Estranged wife">Estranged wife</option>
<option value="Ex brother in law">Ex brother in law</option>
<option value="Ex daughter in law">Ex daughter in law</option>
<option value="Executor">Executor</option>
<option value="Ex husband ex partner">Ex husband ex partner</option>
<option value="Ex sister in law">Ex sister in law</option>
<option value="Ex son in law">Ex son in law</option>
<option value="Ex wife">Ex wife</option>
<option value="Father">Father</option>
<option value="Father in law">Father in law</option>
<option value="Fiancé">Fiancé</option>
<option value="Fiancée">Fiancée</option>
<option value="Financial adviser">Financial adviser</option>
<option value="Foster daughter">Foster daughter</option>
<option value="Foster son">Foster son</option>
<option value="Friend">Friend</option>
<option value="God daughter">God daughter</option>
<option value="God father">God father</option>
<option value="God mother">God mother</option>
<option value="God son">God son</option>
<option value="God sons daughter">God sons daughter</option>
<option value="God sons son">God sons son</option>
<option value="Granddaughter">Granddaughter</option>
<option value="Grandfather">Grandfather</option>
<option value="Grandmother">Grandmother</option>
<option value="Grandson">Grandson</option>
<option value="Great grand daughter">Great grand daughter</option>
<option value="Great grand son">Great grand son</option>
<option value="Great nephew">Great nephew</option>
<option value="Great niece">Great niece</option>
<option value="Half brother in law">Half brother in law</option>
<option value="Half sister in law">Half sister in law</option>
<option value="Half brother">Half brother</option>
<option value="Half sister">Half sister</option>
<option value="Husband">Husband</option>
<option value="Husbands aunt">Husbands aunt</option>
<option value="Husbands brother in law">Husbands brother in law</option>
<option value="Husbands cousin">Husbands cousin</option>
<option value="Husbands daughter">Husbands daughter</option>
<option value="Husbands daughter in law">Husbands daughter in law</option>
<option value="Husbands ex partner">Husbands ex partner</option>
<option value="Husbands ex wife">Husbands ex wife</option>
<option value="Husbands friend">Husbands friend</option>
<option value="Husbands god daughter">Husbands god daughter</option>
<option value="Husbands god son">Husbands god son</option>
<option value="Husbands nephew">Husbands nephew</option>
<option value="Husbands nephews daughter">Husbands nephews daughter</option>
<option value="Husbands nephews son">Husbands nephews son</option>
<option value="Husbands niece">Husbands niece</option>
<option value="Husbands nieces daughter">Husbands nieces daughter</option>
<option value="Husbands nieces son">Husbands nieces son</option>
<option value="Husbands sister in law">Husbands sister in law</option>
<option value="Husbands son">Husbands son</option>
<option value="Husbands son in law">Husbands son in law</option>
<option value="Husbands step brother">Husbands step brother</option>
<option value="Husbands step sister">Husbands step sister</option>
<option value="Husbands uncle">Husbands uncle</option>
<option value="Mother">Mother</option>
<option value="Mother in law">Mother in law</option>
<option value="Nephew">Nephew</option>
<option value="Nephew in law">Nephew in law</option>
<option value="Nephews husband">Nephews husband</option>
<option value="Nephews wife">Nephews wife</option>
<option value="Niece">Niece</option>
<option value="Niece in law">Niece in law</option>
<option value="Nieces husband">Nieces husband</option>
<option value="Nieces wife">Nieces wife</option>
<option value="None">None</option>
<option value="Partner">Partner</option>
<option value="Partners aunt">Partners aunt</option>
<option value="Partners brother">Partners brother</option>
<option value="Partners brother in law">Partners brother in law</option>
<option value="Partners cousin">Partners cousin</option>
<option value="Partners daughter">Partners daughter</option>
<option value="Partners daughter in law">Partners daughter in law</option>
<option value="Partners ex daughter in law">Partners ex daughter in law</option>
<option value="Partners ex husband">Partners ex husband</option>
<option value="Partners ex son in law">Partners ex son in law</option>
<option value="Partners ex wife">Partners ex wife</option>
<option value="Partners father">Partners father</option>
<option value="Partners friend">Partners friend</option>
<option value="Partners god daughter">Partners god daughter</option>
<option value="Partners god son">Partners god son</option>
<option value="Partners grand daughter">Partners grand daughter</option>
<option value="Partners grandson">Partners grandson</option>
<option value="Partners great grand daughter">
    Partners great grand daughter
</option>
<option value="Partners great grand son">Partners great grand son</option>
<option value="Partners great nephew">Partners great nephew</option>
<option value="Partners great niece">Partners great niece</option>
<option value="Partners mother">Partners mother</option>
<option value="Partners nephew">Partners nephew</option>
<option value="Partners niece">Partners niece</option>
<option value="Partners sister">Partners sister</option>
<option value="Partners sister in law">Partners sister in law</option>
<option value="Partners son">Partners son</option>
<option value="Partners so in law">Partners so in law</option>
<option value="Partners step grand daughter">
    Partners step grand daughter
</option>
<option value="Partners step grandson">Partners step grandson</option>
<option value="Partners step daughter">Partners step daughter</option>
<option value="Partners step father">Partners step father</option>
<option value="Partners step mother">Partners step mother</option>
<option value="Partners step son">Partners step son</option>
<option value="Partners uncle">Partners uncle</option>
<option value="Second cousin">Second cousin</option>
<option value="Sister">Sister</option>
<option value="Sister in law">Sister in law</option>
<option value="Sisters partner">Sisters partner</option>
<option value="Solicitor">Solicitor</option>
<option value="Son">Son</option>
<option value="Son in law">Son in law</option>
<option value="Sons partner">Sons partner</option>
<option value="Step daughter in law">Step daughter in law</option>
<option value="Step son in law">Step son in law</option>
<option value="Step brother">Step brother</option>
<option value="Step cousin">Step cousin</option>
<option value="Step daughter">Step daughter</option>
<option value="Step daughters partner">Step daughters partner</option>
<option value="Step father">Step father</option>
<option value="Step father in law">Step father in law</option>
<option value="Step grand daughter">Step grand daughter</option>
<option value="Step grandson">Step grandson</option>
<option value="Step half brother">Step half brother</option>
<option value="Step half sister">Step half sister</option>
<option value="Step mother">Step mother</option>
<option value="Step mother in law">Step mother in law</option>
<option value="Step nephew">Step nephew</option>
<option value="Step niece">Step niece</option>
<option value="Step sister">Step sister</option>
<option value="Step son">Step son</option>
<option value="Step sons partner">Step sons partner</option>
<option value="Uncle">Uncle</option>
<option value="Wife">Wife</option>
<option value="Wife’s aunt">Wife’s aunt</option>
<option value="Wife’s brother">Wife’s brother</option>
<option value="Wife’s brother in law">Wife’s brother in law</option>
<option value="Wife’s cousin">Wife’s cousin</option>
<option value="Wife’s daughter">Wife’s daughter</option>
<option value="Wife’s daughter in law">Wife’s daughter in law</option>
<option value="Wife’s ex husband">Wife’s ex husband</option>
<option value="Wife’s ex partner">Wife’s ex partner</option>
<option value="Wife’s friend">Wife’s friend</option>
<option value="Wife’s god daughter">Wife’s god daughter</option>
<option value="Wife’s god son">Wife’s god son</option>
<option value="Wife’s nephew">Wife’s nephew</option>
<option value="Wife’s nephews daughter">Wife’s nephews daughter</option>
<option value="Wife’s nephews son">Wife’s nephews son</option>
<option value="Wife’s niece">Wife’s niece</option>
<option value="Wife’s nieces daughter">Wife’s nieces daughter</option>
<option value="Wife’s nieces son">Wife’s nieces son</option>
<option value="Wife’s sister">Wife’s sister</option>
<option value="Wife’s sister in law">Wife’s sister in law</option>
<option value="Wife’s son">Wife’s son</option>
<option value="Wife’s son in law">Wife’s son in law</option>
<option value="Wife’s step brother">Wife’s step brother</option>
<option value="Wife’s step sister">Wife’s step sister</option>
<option value="Wife’s uncle">Wife’s uncle</option>
