<template>
  <v-select  :options="options" v-model="relation"></v-select>
</template>

<script>
export default {
  name: "RelationshipSelector",
  model: {
    prop: 'modelValue',
    event: 'change'
  },
  props: [
    'modelValue'
  ],
  data() {
    return {
      options: [
        'Brother',
        'Daughter',
        'Father',
        'Mother',
        'Sister',
        'Son',
        'Accountant',
        'Adviser',
        'Aunt',
        'Brother in Law',
        'Brothers partner',
        'Business partner',
        'Civil partner',
        'Cousin',
        'Daughter in Law',
        'Daughters partner',
        'Estranged husband',
        'Estranged wife',
        'Ex brother in law',
        'Ex daughter in law',
        'Executor',
        'Ex husband ex partner',
        'Ex sister in law',
        'Ex son in law',
        'Ex wife',
        'Father in law',
        'Fiancé',
        'Fiancée',
        'Financial adviser',
        'Foster daughter',
        'Foster son',
        'Friend',
        'God daughter',
        'God father',
        'God son',
        'God sons daughter',
        'God sons son',
        'Granddaughter',
        'Grandfather',
        'Grandmother',
        'Grandson',
        'Great grand daughter',
        'Great grand son',
        'Great nephew',
        'Great niece',
        'Half brother in law',
        'Half sister in law',
        'Half brother',
        'Half sister',
        'Husband',
        'Husbands aunt',
        'Husbands brother in law',
        'Husbands cousin',
        'Husbands daughter',
        'Husbands daughter in law',
        'Husbands ex partner',
        'Husbands ex wife',
        'Husbands friend',
        'Husbands god daughter',
        'Husbands god son',
        'Husbands nephew',
        'Husbands nephews daughter',
        'Husbands nephews son',
        'Husbands niece',
        'Husbands nieces daughter',
        'Husbands nieces son',
        'Husbands sister in law',
        'Husbands son',
        'Husbands son in law',
        'Husbands step brother',
        'Husbands step sister',
        'Husbands uncle',
        'Mother in law',
        'Nephew',
        'Nephew in law',
        'Nephews husband',
        'Nephews wife',
        'Niece',
        'Niece in law',
        'Nieces husband',
        'Nieces wife',
        'Partner',
        'Partners aunt',
        'Partners brother',
        'Partners brother in law',
        'Partners cousin',
        'Partners daughter',
        'Partners daughter in law',
        'Partners ex daughter in law',
        'Partners ex husband',
        'Partners ex son in law',
        'Partners ex wife',
        'Partners father',
        'Partners friend',
        'Partners god daughter',
        'Partners god son',
        'Partners grand daughter',
        'Partners grandson',
        'Partners great grand daughter',
        'Partners great grand son',
        'Partners great nephew',
        'Partners great niece',
        'Partners mother',
        'Partners nephew',
        'Partners niece',
        'Partners sister',
        'Partners sister in law',
        'Partners son',
        'Partners so in law',
        'Partners step grand daughter',
        'Partners step grandson',
        'Partners step daughter',
        'Partners step father',
        'Partners step mother',
        'Partners step son',
        'Partners uncle',
        'Second cousin',
        'Sister in law',
        'Sisters partner',
        'Solicitor',
        'Son in law',
        'Sons partner',
        'Step daughter in law',
        'Step son in law',
        'Step brother',
        'Step cousin',
        'Step daughter',
        'Step daughters partner',
        'Step father',
        'Step father in law',
        'Step grand daughter',
        'Step grandson',
        'Step half brother',
        'Step half sister',
        'Step mother',
        'Step mother in law',
        'Step nephew',
        'Step niece',
        'Step sister',
        'Step son',
        'Step sons partner',
        'Uncle',
        'Wife',
        'Wife’s aunt',
        'Wife’s brother',
        'Wife’s brother in law',
        'Wife’s cousin',
        'Wife’s daughter',
        'Wife’s daughter in law',
        'Wife’s ex husband',
        'Wife’s ex partner',
        'Wife’s friend',
        'Wife’s god daughter',
        'Wife’s god son',
        'Wife’s nephew',
        'Wife’s nephews daughter',
        'Wife’s nephews son',
        'Wife’s niece',
        'Wife’s nieces daughter',
        'Wife’s nieces son',
        'Wife’s sister',
        'Wife’s sister in law',
        'Wife’s son',
        'Wife’s son in law',
        'Wife’s step brother',
        'Wife’s step sister',
        'Wife’s uncle'
      ],
      relation: ''
    }
  },
  watch: {
    relation(value) {
      this.$emit('change', value)
    }
  }
}
</script>

<style scoped>

</style>
